"""STEM taxonomy: disciplines, their subfields and the keywords used to detect them.

This module is the single source of truth for classification. The frontend
receives a copy of it (labels only) inside the generated data file, so adding a
subfield here is enough to make it show up in the UI.

Keyword conventions
-------------------
* Keywords are matched case-insensitively on word boundaries.
* A trailing ``*`` means "prefix match" (``nano*`` matches ``nanowire``).
* ``degree_terms`` are the words that appear when a posting *requires* a degree
  in this discipline ("MSc in Physics", "physicist", "background in
  electrical engineering"). They power the "required background" filter.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Subfield:
    id: str
    label: str
    keywords: tuple[str, ...]


@dataclass(frozen=True)
class Discipline:
    id: str
    label: str
    keywords: tuple[str, ...]
    degree_terms: tuple[str, ...]
    subfields: tuple[Subfield, ...] = field(default_factory=tuple)


def _sf(id: str, label: str, *keywords: str) -> Subfield:
    return Subfield(id, label, tuple(keywords))


DISCIPLINES: tuple[Discipline, ...] = (
    Discipline(
        "physics", "Physics",
        keywords=("physics", "physicist", "photonics", "optics", "quantum", "astrophysics",
                  "cosmology", "plasma physics", "spectroscopy", "laser*"),
        degree_terms=("physics", "physicist", "physicists", "applied physics",
                      "engineering physics", "astrophysics", "astronomy"),
        subfields=(
            _sf("quantum-computing", "Quantum Computing & Information",
                "quantum computing", "quantum computer*", "qubit*", "quantum information",
                "quantum error correction", "quantum algorithm*", "quantum software",
                "quantum hardware", "superconducting circuit*", "trapped ion*", "neutral atom*",
                "quantum technolog*", "quantum communication", "quantum cryptography",
                "quantum sensing", "quantum key distribution"),
            _sf("condensed-matter", "Condensed Matter",
                "condensed matter", "solid state physics", "solid-state physics",
                "superconductiv*", "topological", "strongly correlated", "magnetism",
                "spintronics", "2d materials", "graphene", "many-body", "quantum materials"),
            _sf("nanoscience", "Nanoscience & Nanotechnology",
                "nanoscience", "nanotechnolog*", "nanoscale", "nanostructur*", "nanomaterial*",
                "nanoparticle*", "nanophotonics", "nanofabrication", "nanowire*"),
            _sf("surface-physics", "Surface & Interface Physics",
                "surface physics", "surface science", "thin film*", "interface physics",
                "scanning tunneling", "stm", "afm", "atomic force microscop*",
                "photoemission", "arpes", "epitax*", "molecular beam epitaxy"),
            _sf("astrophysics", "Astrophysics & Cosmology",
                "astrophysic*", "astronomy", "astronomer", "cosmolog*", "galax*",
                "exoplanet*", "dark matter", "dark energy", "gravitational wave*",
                "radio astronomy", "telescope*", "stellar", "black hole*", "space science"),
            _sf("particle-physics", "Particle & Nuclear Physics",
                "particle physics", "high energy physics", "high-energy physics", "hep",
                "nuclear physics", "collider", "lhc", "neutrino*", "hadron*", "detector physics",
                "accelerator physics", "particle accelerator*", "standard model"),
            _sf("optics-photonics", "Optics & Photonics",
                "optics", "photonic*", "laser*", "optical", "ultrafast", "nonlinear optics",
                "quantum optics", "integrated photonics", "fiber optic*", "metamaterial*"),
            _sf("atomic-molecular", "Atomic, Molecular & Optical",
                "atomic physics", "molecular physics", "amo", "cold atoms", "ultracold",
                "bose-einstein", "atom interferometr*", "optical clock*", "precision measurement*"),
            _sf("plasma-fusion", "Plasma & Fusion",
                "plasma physics", "fusion energy", "fusion reactor*", "nuclear fusion", "tokamak", "stellarator",
                "inertial confinement", "magnetic confinement"),
            _sf("biophysics", "Biophysics & Soft Matter",
                "biophysic*", "soft matter", "active matter", "polymer physics", "complex fluids",
                "single-molecule", "biological physics"),
            _sf("theoretical-physics", "Theoretical & Mathematical Physics",
                "theoretical physics", "mathematical physics", "string theory", "quantum field theory",
                "general relativity", "statistical physics", "statistical mechanics",
                "quantum gravity", "lattice qcd"),
            _sf("computational-physics", "Computational Physics",
                "computational physics", "molecular dynamics", "monte carlo", "dft",
                "density functional theory", "ab initio", "first-principles", "first principles"),
            _sf("medical-physics", "Medical Physics",
                "medical physics", "medical physicist", "radiotherapy", "radiation therapy",
                "dosimetry", "medical imaging", "mri physics", "nuclear medicine"),
            _sf("geophysics", "Geophysics & Atmospheric Physics",
                "geophysic*", "seismolog*", "atmospheric physics", "atmospheric science",
                "climate physics", "space weather", "oceanograph*"),
            _sf("instrumentation", "Instrumentation & Detectors",
                "instrumentation", "detector*", "cryogenic*", "sensors", "metrology",
                "superconducting detector*", "mkid*", "tes bolometer*", "fpga"),
        ),
    ),
    Discipline(
        "chemistry", "Chemistry",
        keywords=("chemistry", "chemist", "chemical", "catalysis", "synthesis", "spectroscopy"),
        degree_terms=("chemistry", "chemist", "chemists", "chemical sciences", "biochemistry"),
        subfields=(
            _sf("organic-chemistry", "Organic Chemistry",
                "organic chemistry", "organic synthesis", "medicinal chemistry", "total synthesis"),
            _sf("inorganic-chemistry", "Inorganic Chemistry",
                "inorganic chemistry", "coordination chemistry", "organometallic*", "main group"),
            _sf("physical-chemistry", "Physical Chemistry",
                "physical chemistry", "chemical physics", "spectroscop*", "kinetics", "photochemistry"),
            _sf("analytical-chemistry", "Analytical Chemistry",
                "analytical chemistry", "mass spectrometry", "chromatograph*", "hplc", "nmr",
                "instrumental analysis"),
            _sf("computational-chemistry", "Computational & Theoretical Chemistry",
                "computational chemistry", "theoretical chemistry", "quantum chemistry",
                "molecular modelling", "molecular modeling", "molecular dynamics", "dft"),
            _sf("catalysis", "Catalysis",
                "catalysis", "catalyst*", "electrocatalysis", "photocatalysis", "heterogeneous catalysis",
                "homogeneous catalysis"),
            _sf("electrochemistry", "Electrochemistry & Energy Storage",
                "electrochemistry", "electrochemical", "batter*", "lithium-ion", "fuel cell*",
                "electrolyte*", "energy storage", "supercapacitor*"),
            _sf("polymer-chemistry", "Polymers & Soft Materials",
                "polymer*", "macromolecul*", "soft materials", "hydrogel*"),
            _sf("biochemistry", "Biochemistry & Chemical Biology",
                "biochemistry", "chemical biology", "enzym*", "protein chemistry", "bioorganic"),
            _sf("materials-chemistry", "Materials Chemistry",
                "materials chemistry", "solid state chemistry", "solid-state chemistry",
                "metal-organic framework*", "mof*", "porous materials", "crystal growth"),
            _sf("green-chemistry", "Environmental & Green Chemistry",
                "green chemistry", "environmental chemistry", "sustainable chemistry",
                "atmospheric chemistry", "co2 conversion", "carbon capture"),
        ),
    ),
    Discipline(
        "mathematics", "Mathematics",
        keywords=("mathematics", "mathematician", "mathematical", "statistics", "statistician",
                  "probability", "algebra", "geometry", "topology"),
        degree_terms=("mathematics", "mathematician", "mathematicians", "applied mathematics",
                      "statistics", "statistician", "maths", "math"),
        subfields=(
            _sf("pure-math", "Pure Mathematics",
                "algebra", "algebraic geometry", "number theory", "topology", "geometry",
                "representation theory", "category theory", "pure mathematics", "logic",
                "combinatorics", "group theory"),
            _sf("analysis-pde", "Analysis & PDEs",
                "analysis", "partial differential equation*", "pde*", "functional analysis",
                "harmonic analysis", "dynamical systems", "ergodic"),
            _sf("applied-math", "Applied & Computational Mathematics",
                "applied mathematics", "numerical analysis", "scientific computing",
                "computational mathematics", "optimization", "optimisation", "inverse problems",
                "mathematical modelling", "mathematical modeling", "uncertainty quantification"),
            _sf("probability-statistics", "Probability & Statistics",
                "probability", "statistics", "statistical", "stochastic*", "bayesian",
                "biostatistics", "econometrics", "time series"),
            _sf("math-physics", "Mathematical Physics",
                "mathematical physics", "quantum field theory", "integrable systems"),
            _sf("data-science-math", "Data Science & Machine Learning Theory",
                "learning theory", "statistical learning", "data science", "machine learning"),
            _sf("financial-math", "Financial Mathematics",
                "financial mathematics", "quantitative finance", "actuarial", "risk modelling",
                "quantitative analyst", "quantitative researcher"),
            _sf("operations-research", "Operations Research",
                "operations research", "operational research", "combinatorial optimization",
                "integer programming", "scheduling"),
        ),
    ),
    Discipline(
        "computer-science", "Computer Science",
        keywords=("computer science", "software", "machine learning", "artificial intelligence",
                  "computing", "algorithms", "data science", "informatics", "developer", "sql",
                  "devops", "site reliability", "sre", "kubernetes", "cloud infrastructure",
                  "backend", "frontend", "full stack", "full-stack", "programmer", "data engineer"),
        degree_terms=("computer science", "computer scientist", "informatics", "software engineering",
                      "computing", "computer engineering", "data science"),
        subfields=(
            _sf("machine-learning", "Machine Learning & AI",
                "machine learning", "deep learning", "artificial intelligence", "ai", "neural network*",
                "reinforcement learning", "computer vision", "natural language processing", "nlp",
                "large language model*", "llm*", "generative ai"),
            _sf("software-engineering", "Software Engineering",
                "software engineer*", "software development", "backend", "frontend", "full stack",
                "full-stack", "devops", "software developer"),
            _sf("hpc", "High-Performance & Scientific Computing",
                "high performance computing", "high-performance computing", "hpc", "gpu", "cuda",
                "parallel computing", "supercomput*", "scientific computing"),
            _sf("theory-cs", "Theoretical Computer Science",
                "theoretical computer science", "complexity theory", "algorithms", "formal methods",
                "formal verification", "programming languages", "cryptography"),
            _sf("security", "Cybersecurity",
                "cybersecurity", "cyber security", "security engineer*", "information security",
                "cryptograph*", "privacy"),
            _sf("data-engineering", "Data Science & Engineering",
                "data scientist", "data science", "data engineer*", "big data", "data analytics",
                "data analysis"),
            _sf("robotics", "Robotics & Autonomous Systems",
                "robotic*", "robot*", "autonomous systems", "autonomous vehicle*", "slam",
                "motion planning", "perception"),
            _sf("hci", "Human-Computer Interaction",
                "human-computer interaction", "hci", "user experience", "visualization",
                "visualisation"),
            _sf("bioinformatics", "Bioinformatics & Computational Biology",
                "bioinformatic*", "computational biology", "genomics", "systems biology"),
        ),
    ),
    Discipline(
        "electrical-engineering", "Electrical & Electronic Engineering",
        keywords=("electrical engineering", "electronic engineering", "electronics", "circuit*",
                  "signal processing", "power systems", "semiconductor*", "fpga", "asic", "rf",
                  "mixed-signal", "mixed signal", "analog", "pcb", "rtl", "design verification",
                  "verification engineer", "hardware engineer*", "electrical engineer*", "silicon",
                  "firmware"),
        degree_terms=("electrical engineering", "electronic engineering", "electronics engineering",
                      "electrical and electronic engineering", "electrical engineer",
                      "electronics", "ee", "electrical and computer engineering", "ece",
                      "telecommunications engineering"),
        subfields=(
            _sf("power-energy", "Power Systems & Energy",
                "power systems", "power electronics", "power grid*", "smart grid", "renewable energy",
                "photovoltaic*", "solar", "wind energy", "energy systems", "electric machines",
                "high voltage"),
            _sf("microelectronics", "Microelectronics & Semiconductors",
                "microelectronics", "semiconductor*", "vlsi", "asic", "integrated circuit*",
                "chip design", "cmos", "analog design", "mixed-signal", "device physics",
                "cleanroom", "lithography", "wafer"),
            _sf("embedded", "Embedded Systems & FPGA",
                "embedded", "fpga", "firmware", "microcontroller*", "rtos", "verilog", "vhdl",
                "hardware design", "digital design"),
            _sf("signal-processing", "Signal Processing",
                "signal processing", "dsp", "image processing", "audio processing",
                "radar", "sonar", "estimation theory"),
            _sf("communications", "Communications & RF",
                "rf", "radio frequency", "microwave*", "antenna*", "wireless", "5g", "6g",
                "telecommunication*", "communication systems", "millimeter wave", "mmwave"),
            _sf("control", "Control Systems",
                "control systems", "control engineering", "control theory", "model predictive control",
                "mpc", "system identification", "mechatronics"),
            _sf("optoelectronics", "Optoelectronics",
                "optoelectronic*", "photodetector*", "light-emitting diode*", "silicon photonics", "laser diode*"),
        ),
    ),
    Discipline(
        "mechanical-engineering", "Mechanical Engineering",
        keywords=("mechanical engineering", "mechanical engineer", "thermodynamics", "fluid*",
                  "mechanics", "manufacturing", "mechanical design", "cad", "solidworks", "catia",
                  "tire", "tyre", "powertrain", "drivetrain", "hvac"),
        degree_terms=("mechanical engineering", "mechanical engineer", "mechatronics",
                      "mechanical and aerospace engineering"),
        subfields=(
            _sf("fluid-dynamics", "Fluid Dynamics & CFD",
                "fluid dynamics", "fluid mechanics", "cfd", "computational fluid dynamics",
                "turbulence", "aerodynamics", "multiphase flow", "heat transfer"),
            _sf("solid-mechanics", "Solid Mechanics & Structures",
                "solid mechanics", "structural mechanics", "finite element*", "fem", "fea",
                "fracture mechanics", "fatigue", "structural analysis", "composites"),
            _sf("thermal", "Thermal & Energy Engineering",
                "thermodynamics", "thermal engineering", "heat transfer", "combustion",
                "hvac", "turbomachinery", "heat pump*", "thermal management"),
            _sf("manufacturing", "Manufacturing & Production",
                "manufacturing", "additive manufacturing", "3d printing", "machining",
                "production engineering", "industrial engineering", "lean"),
            _sf("mechatronics", "Mechatronics & Robotics",
                "mechatronic*", "robotic*", "actuator*", "motion control", "mechanical design"),
            _sf("acoustics", "Acoustics & Vibrations",
                "acoustic*", "vibration*", "noise", "ultrasound"),
            _sf("biomechanics", "Biomechanics",
                "biomechanic*", "medical devices", "prosthe*"),
        ),
    ),
    Discipline(
        "aerospace-engineering", "Aerospace Engineering",
        keywords=("aerospace", "aeronautic*", "astronautic*", "spacecraft", "satellite*",
                  "rocket*", "propulsion", "avionics", "space systems"),
        degree_terms=("aerospace engineering", "aeronautical engineering", "astronautical engineering",
                      "aerospace engineer", "aeronautics"),
        subfields=(
            _sf("spacecraft", "Spacecraft & Satellites",
                "spacecraft", "satellite*", "space systems", "orbital mechanics", "gnc",
                "guidance navigation and control", "cubesat*", "space mission*"),
            _sf("propulsion", "Propulsion",
                "propulsion", "rocket engine*", "jet engine*", "electric propulsion",
                "combustion", "turbine*"),
            _sf("aerodynamics", "Aerodynamics & Flight",
                "aerodynamic*", "flight dynamics", "flight control", "aircraft", "uav*", "drone*"),
            _sf("avionics", "Avionics & Space Electronics",
                "avionics", "flight software", "space electronics", "radiation hardened"),
        ),
    ),
    Discipline(
        "chemical-engineering", "Chemical Engineering",
        keywords=("chemical engineering", "process engineering", "reactor*", "separation*"),
        degree_terms=("chemical engineering", "chemical engineer", "process engineering",
                      "chemical and biomolecular engineering"),
        subfields=(
            _sf("process-engineering", "Process Engineering & Design",
                "process engineering", "process design", "process control", "process simulation",
                "aspen", "scale-up", "unit operations"),
            _sf("reaction-engineering", "Reaction Engineering",
                "reaction engineering", "reactor design", "chemical reactor*", "kinetics"),
            _sf("separation", "Separation Processes",
                "separation*", "distillation", "membrane*", "adsorption", "crystallization",
                "crystallisation"),
            _sf("bioprocess", "Bioprocess Engineering",
                "bioprocess*", "fermentation", "bioreactor*", "biomanufacturing"),
            _sf("energy-chem", "Energy & Sustainability",
                "hydrogen", "electrolysis", "carbon capture", "biofuel*", "e-fuels", "sustainability",
                "circular economy", "recycling"),
        ),
    ),
    Discipline(
        "materials-science", "Materials Science",
        keywords=("materials science", "materials engineering", "metallurgy", "ceramics",
                  "polymers", "composites", "thin films"),
        degree_terms=("materials science", "materials engineering", "materials scientist",
                      "metallurgy", "materials science and engineering"),
        subfields=(
            _sf("metals", "Metals & Metallurgy",
                "metallurg*", "alloy*", "steel", "metals", "welding", "corrosion"),
            _sf("ceramics", "Ceramics & Glass", "ceramic*", "glass", "oxides"),
            _sf("functional-materials", "Functional & Electronic Materials",
                "functional materials", "electronic materials", "semiconductor materials",
                "magnetic materials", "ferroelectric*", "piezoelectric*", "perovskite*",
                "2d materials", "thermoelectric*"),
            _sf("energy-materials", "Energy Materials",
                "energy materials", "battery materials", "cathode*", "anode*", "solar cell*",
                "photovoltaic*", "solid-state batter*"),
            _sf("characterization", "Materials Characterization",
                "characteri?ation", "electron microscop*", "x-ray diffraction",
                "xrd", "synchrotron", "neutron scattering", "tomography"),
            _sf("computational-materials", "Computational Materials Science",
                "computational materials", "materials modelling", "materials modeling",
                "materials informatics", "dft", "phase-field", "molecular dynamics"),
            _sf("biomaterials", "Biomaterials", "biomaterial*", "tissue engineering", "scaffold*"),
        ),
    ),
    Discipline(
        "civil-engineering", "Civil & Environmental Engineering",
        keywords=("civil engineering", "structural engineering", "geotechnical", "hydraulic*",
                  "environmental engineering", "transportation engineering"),
        degree_terms=("civil engineering", "civil engineer", "structural engineering",
                      "environmental engineering", "geotechnical engineering"),
        subfields=(
            _sf("structural", "Structural Engineering",
                "structural engineering", "structural design", "earthquake engineering",
                "bridge*", "concrete", "steel structures", "timber"),
            _sf("geotechnical", "Geotechnical Engineering",
                "geotechnic*", "soil mechanics", "foundation*", "tunnel*", "rock mechanics"),
            _sf("water", "Water & Hydraulics",
                "hydraulic*", "hydrology", "water resources", "wastewater", "water treatment",
                "flood*", "coastal engineering"),
            _sf("transportation", "Transportation & Infrastructure",
                "transportation engineering", "transport planning", "traffic engineering", "civil infrastructure",
                "transport infrastructure", "railway engineering", "urban mobility"),
            _sf("environmental-eng", "Environmental Engineering",
                "environmental engineering", "pollution", "air quality", "waste management",
                "remediation"),
        ),
    ),
    Discipline(
        "biomedical-engineering", "Biomedical Engineering",
        keywords=("biomedical engineering", "bioengineering", "medical device*", "medical imaging",
                  "biomaterials", "neuroengineering"),
        degree_terms=("biomedical engineering", "bioengineering", "biomedical engineer",
                      "biological engineering"),
        subfields=(
            _sf("medical-imaging", "Medical Imaging",
                "medical imaging", "mri", "computed tomography", "pet imaging", "ultrasound imaging", "image reconstruction"),
            _sf("medical-devices", "Medical Devices",
                "medical device*", "implant*", "wearable*", "biosensor*", "point-of-care"),
            _sf("neuroengineering", "Neuroengineering",
                "neuroengineering", "brain-computer interface*", "bci", "neural interface*",
                "neuroprosthe*", "electrophysiology"),
            _sf("tissue-engineering", "Tissue Engineering & Biomaterials",
                "tissue engineering", "biomaterial*", "regenerative medicine", "organ-on-chip",
                "organ on a chip", "microfluidic*"),
        ),
    ),
    Discipline(
        "earth-sciences", "Earth & Environmental Sciences",
        keywords=("earth science*", "geology", "geoscience*", "climate", "oceanograph*",
                  "atmospheric", "environmental science", "hydrology", "glaciolog*"),
        degree_terms=("geology", "geosciences", "earth sciences", "earth science",
                      "environmental science", "environmental sciences", "geophysics",
                      "meteorology", "oceanography", "climate science"),
        subfields=(
            _sf("climate", "Climate & Atmosphere",
                "climate", "atmospher*", "meteorolog*", "weather", "climate model*", "aerosol*"),
            _sf("geology", "Geology & Geochemistry",
                "geology", "geochemistry", "mineralogy", "petrology", "sedimentology", "tectonic*",
                "volcanolog*"),
            _sf("oceanography", "Oceanography & Cryosphere",
                "oceanograph*", "marine science", "glacio*", "sea ice", "cryosphere", "polar"),
            _sf("remote-sensing", "Remote Sensing & Earth Observation",
                "remote sensing", "earth observation", "satellite imagery", "sar", "lidar", "gis"),
            _sf("ecology-env", "Ecology & Environment",
                "ecology", "biodiversity", "ecosystem*", "conservation", "environmental monitoring"),
        ),
    ),
    Discipline(
        "life-sciences", "Life Sciences",
        keywords=("biology", "biologist", "molecular biology", "genetics", "neuroscience",
                  "microbiology", "bioinformatics", "life sciences", "biotechnology"),
        degree_terms=("biology", "biologist", "life sciences", "molecular biology", "biotechnology",
                      "neuroscience", "microbiology", "genetics", "biochemistry"),
        subfields=(
            _sf("molecular-biology", "Molecular & Cell Biology",
                "molecular biology", "cell biology", "crispr", "gene editing", "protein*",
                "structural biology", "cryo-em"),
            _sf("neuroscience", "Neuroscience", "neuroscien*", "neurobiolog*", "brain research", "cognitive neuroscience"),
            _sf("genetics-genomics", "Genetics & Genomics",
                "genetic*", "genomic*", "sequencing", "transcriptomic*", "epigenetic*"),
            _sf("microbiology", "Microbiology & Immunology",
                "microbiolog*", "immunolog*", "virolog*", "bacteria*", "microbiome"),
            _sf("biotech", "Biotechnology",
                "biotechnolog*", "synthetic biology", "biopharma*", "antibod*", "drug discovery"),
        ),
    ),
)

DISCIPLINE_BY_ID = {d.id: d for d in DISCIPLINES}


# Map EURAXESS "Research Field" top-level labels (the part before "»") and some
# specific sub-labels to our discipline / subfield ids. Lower-case keys.
EURAXESS_FIELD_MAP: dict[str, tuple[str | None, str | None]] = {
    # top-level
    "physics": ("physics", None),
    "astronomy": ("physics", "astrophysics"),
    "chemistry": ("chemistry", None),
    "mathematics": ("mathematics", None),
    "computer science": ("computer-science", None),
    "engineering": (None, None),  # too broad: decided by sub-label / keywords
    "technology": (None, None),
    "environmental science": ("earth-sciences", None),
    "geosciences": ("earth-sciences", None),
    "biological sciences": ("life-sciences", None),
    # physics sub-labels
    "astrophysics": ("physics", "astrophysics"),
    "cosmology": ("physics", "astrophysics"),
    "applied physics": ("physics", None),
    "biophysics": ("physics", "biophysics"),
    "chemical physics": ("physics", "atomic-molecular"),
    "classical mechanics": ("physics", "theoretical-physics"),
    "computational physics": ("physics", "computational-physics"),
    "condensed matter properties": ("physics", "condensed-matter"),
    "solid state physics": ("physics", "condensed-matter"),
    "surface physics": ("physics", "surface-physics"),
    "electromagnetism": ("physics", None),
    "electronics": ("electrical-engineering", None),
    "mathematical physics": ("physics", "theoretical-physics"),
    "metrology": ("physics", "instrumentation"),
    "optics": ("physics", "optics-photonics"),
    "quantum mechanics": ("physics", "quantum-computing"),
    "relativity": ("physics", "theoretical-physics"),
    "statistical physics": ("physics", "theoretical-physics"),
    "thermodynamics": ("physics", None),
    "nuclear physics": ("physics", "particle-physics"),
    "quantum technology": ("physics", "quantum-computing"),
    "nanotechnology": ("physics", "nanoscience"),
    # chemistry sub-labels
    "analytical chemistry": ("chemistry", "analytical-chemistry"),
    "applied chemistry": ("chemistry", None),
    "biochemistry": ("chemistry", "biochemistry"),
    "computational chemistry": ("chemistry", "computational-chemistry"),
    "heterogeneous catalysis": ("chemistry", "catalysis"),
    "homogeneous catalysis": ("chemistry", "catalysis"),
    "inorganic chemistry": ("chemistry", "inorganic-chemistry"),
    "molecular chemistry": ("chemistry", None),
    "organic chemistry": ("chemistry", "organic-chemistry"),
    "physical chemistry": ("chemistry", "physical-chemistry"),
    "structural chemistry": ("chemistry", "materials-chemistry"),
    "crystal growth": ("chemistry", "materials-chemistry"),
    "solar chemistry": ("chemistry", "green-chemistry"),
    # mathematics
    "algebra": ("mathematics", "pure-math"),
    "geometry": ("mathematics", "pure-math"),
    "number theory": ("mathematics", "pure-math"),
    "combinatorial analysis": ("mathematics", "pure-math"),
    "discrete mathematics": ("mathematics", "pure-math"),
    "mathematical logic": ("mathematics", "pure-math"),
    "mathematical analysis": ("mathematics", "analysis-pde"),
    "applied mathematics": ("mathematics", "applied-math"),
    "computational mathematics": ("mathematics", "applied-math"),
    "probability theory": ("mathematics", "probability-statistics"),
    "statistics": ("mathematics", "probability-statistics"),
    "algorithms": ("computer-science", "theory-cs"),
    # computer science
    "informatics": ("computer-science", None),
    "programming": ("computer-science", "software-engineering"),
    "database management": ("computer-science", "data-engineering"),
    "modelling tools": ("computer-science", None),
    "systems design": ("computer-science", None),
    "computer architecture": ("electrical-engineering", "embedded"),
    "computer hardware": ("electrical-engineering", "embedded"),
    "digital systems": ("electrical-engineering", "embedded"),
    "cybernetics": ("electrical-engineering", "control"),
    "information technology": ("computer-science", None),
    # engineering
    "aerospace engineering": ("aerospace-engineering", None),
    "space technology": ("aerospace-engineering", "spacecraft"),
    "biological engineering": ("biomedical-engineering", None),
    "biomaterial engineering": ("biomedical-engineering", "tissue-engineering"),
    "biomedical engineering": ("biomedical-engineering", None),
    "medical technology": ("biomedical-engineering", "medical-devices"),
    "chemical engineering": ("chemical-engineering", None),
    "chemical technology": ("chemical-engineering", None),
    "process engineering": ("chemical-engineering", "process-engineering"),
    "civil engineering": ("civil-engineering", None),
    "water resources engineering": ("civil-engineering", "water"),
    "geological engineering": ("civil-engineering", "geotechnical"),
    "surveying": ("civil-engineering", None),
    "communication engineering": ("electrical-engineering", "communications"),
    "telecommunications technology": ("electrical-engineering", "communications"),
    "communication technology": ("electrical-engineering", "communications"),
    "computer engineering": ("electrical-engineering", "embedded"),
    "control engineering": ("electrical-engineering", "control"),
    "electrical engineering": ("electrical-engineering", None),
    "electrical technology": ("electrical-engineering", None),
    "electronic engineering": ("electrical-engineering", None),
    "energy technology": ("electrical-engineering", "power-energy"),
    "micro-technology": ("electrical-engineering", "microelectronics"),
    "optronics": ("electrical-engineering", "optoelectronics"),
    "instrumentation technology": ("physics", "instrumentation"),
    "measurement technology": ("physics", "instrumentation"),
    "materials engineering": ("materials-science", None),
    "materials technology": ("materials-science", None),
    "mechanical engineering": ("mechanical-engineering", None),
    "precision engineering": ("mechanical-engineering", None),
    "microengineering": ("mechanical-engineering", None),
    "thermal engineering": ("mechanical-engineering", "thermal"),
    "maritime engineering": ("mechanical-engineering", None),
    "industrial engineering": ("mechanical-engineering", "manufacturing"),
    "production technology": ("mechanical-engineering", "manufacturing"),
    "design engineering": ("mechanical-engineering", None),
    "simulation engineering": ("mechanical-engineering", None),
    "nuclear engineering": ("physics", "plasma-fusion"),
    "nuclear technology": ("physics", "particle-physics"),
    "acoustics": ("mechanical-engineering", "acoustics"),
    "remote sensing": ("earth-sciences", "remote-sensing"),
    "environmental technology": ("civil-engineering", "environmental-eng"),
    "water technology": ("civil-engineering", "water"),
    # earth / life sciences
    "earth science": ("earth-sciences", None),
    "geology": ("earth-sciences", "geology"),
    "hydrology": ("earth-sciences", None),
    "global change": ("earth-sciences", "climate"),
    "ecology": ("earth-sciences", "ecology-env"),
    "biodiversity": ("earth-sciences", "ecology-env"),
    "water science": ("earth-sciences", None),
    "biology": ("life-sciences", None),
    "biotechnology": ("life-sciences", "biotech"),
    "neurosciences": ("life-sciences", "neuroscience"),
    "neurobiology": ("life-sciences", "neuroscience"),
    "neuroinformatics": ("life-sciences", "neuroscience"),
}

# EURAXESS research-field facet ids for the STEM top-level fields we crawl.
EURAXESS_STEM_FIELD_IDS = (
    345,  # Physics
    34,   # Astronomy
    47,   # Chemistry
    298,  # Mathematics
    78,   # Computer science
    164,  # Engineering
    401,  # Technology
    195,  # Environmental science
    219,  # Geosciences
    196,  # Earth science
    38,   # Biological sciences
)


def public_taxonomy() -> list[dict]:
    """Labels-only view of the taxonomy, embedded in the generated data file."""
    return [
        {
            "id": d.id,
            "label": d.label,
            "subfields": [{"id": s.id, "label": s.label} for s in d.subfields],
        }
        for d in DISCIPLINES
    ]
